name: Continuous Integration

on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Build project
        run: make build
      - name: Run linter
        run: make linter
